swagger: "2.0"
info:
  title: CoBadge Issuers
  description: The issuer can handle the co-badge search [see](https://www.pivotaltracker.com/story/show/176575992).
  version: "0.1"
paths:
definitions:
  CoBadgeIssuers:
    type: object
    additionalProperties:
      type: boolean