#
# This file contains the metadata for the services approved in the IO app
#
# The key for each service is the serviceId.
# All fields are optional.
#
---
5a563817fcc896087002ea46c49a:
  description: |
    IO è l’applicazione sperimentale (attualmente in fase di closed beta) che permette ai cittadini
    di gestire direttamente dal proprio smartphone i rapporti con la Pubblica Amministrazione Italiana
    e l’accesso ai servizi pubblici.

    Ti invierà messaggi su come usare l'applicazione, aggiornamenti sul progetto o sulle funzionlità dell'app,
    richieste di feedback e altre istruzioni utili alla sperimentazione.
    
    IO è un progetto della Presidenza del Consiglio dei Ministri realizzato dal Team per la Trasformazione Digitale
    in collaborazione con Agid.

  web_url: https://io.italia.it
  email: io-testing@teamdigitale.governo.it

5a25abf4fcc89605c082f042c49a:
  description: |
    Il servizio dell’Anagrafe del Comune di Milano. Tramite IO potrai:

    * Ricevere notifiche sulla scadenza dei tuoi documenti di identità

  web_url: http://www.comune.milano.it/wps/portal/ist/it/servizi/servizionline/pagine_servizi/anagrafe/anagrafe_link_servizi_online
  privacy_url: http://www.palazzorealemilano.it/wps/portal/luogo/palazzoreale/footer/linkinterni/privacy
  phone: +39 02 0202
  email: anagrafe@comune.milano.it
  pec: anagrafe@pec.comune.milano.it

5b4f7512a9ab400f2417f0ccc49a:
  description: |
    Il servizio della Polizia Municipale del Comune di Cagliari. Tramite IO potrai:

      * Riceve notifiche relative pagamenti necessati per sanzioni al Codice della Strada
      * Effettuare il pagamento delle sanzioni per violazioni al Codice della Strada

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://www.comune.cagliari.it/portale/it/servizio_polizia_municipale.page
  address: Via Avicenna - 09131 Cagliari
  phone: +39 0800230606
  email: pm.ced@comune.cagliari.it
  pec: poliziamunicipale@comune.cagliari.legalmail.it

5b928ef65aaa2928c0319563c49a:
  description: |
    Il servizio della Protezione Civile del Comune di Cagliari. Tramite IO potrai:

      * Ricevere, in tempo reale, notifiche di avviso (preallarme o allarme) su criticità ambientali.

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://servizi.comune.cagliari.it/portale/it/servizio_sms.page
  address: Via Giuseppe Mercalli, 31 - 09129 Cagliari
  phone: +39 070 6776905
  email: protezione.civile@comune.cagliari.it
  pec: protocollogenerale@comune.cagliari.legalmail.it

5b87a75d34234f1170e79deec49a:
  description: |
    Il servizio sulla Viabilità del Comune di Cagliari. Tramite IO potrai:

      * Essere avvisato in tempi utili sulla scadenza del tuo permesso ZTL
      * Richiedere e pagare (se necessario) il tuo nuovo permesso ZTL

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://servizi.comune.cagliari.it/portale/it/richiesta_rinn_pass_ztl.page
  address: Piazza A. De Gasperi, 2 - 09125 Cagliari
  phone: +39 070 6778303
  email: ufficioztl@comune.cagliari.it
  pec: protocollogenerale@comune.cagliari.legalmail.it

# 
# Demo services.
#
01CT1SFF37VFZDNFWG2SRH6RDN:
  description: |
    IO è l’applicazione sperimentale (attualmente in fase di closed beta) che permette ai cittadini di gestire
    direttamente dal proprio smartphone i rapporti con la Pubblica Amministrazione Italiana e l’accesso ai servizi pubblici.  
    Ti invierà messaggi su come usare l'applicazione, aggiornamenti sul progetto o sulle funzionlità dell'app, 
    richieste di feedback e altre istruzioni utili alla sperimentazione.

  web_url: https://io.italia.it
  email: io-testing@teamdigitale.governo.it

01CT1B34NGZ51TVB6992ET4HYX:
  description: |
    Il servizio dei Tributi del Comune di Milano.
    Tramite IO potrai:

      * Ricevere notifiche sulla scadenza delle rate TARI
      * Pagare le tue rate della TARI

  privacy_url: http://www.palazzorealemilano.it/wps/portal/luogo/palazzoreale/footer/linkinterni/privacy
  web_url: https://www.comune.milano.it/wps/portal/ist/it/servizi/servizionline/pagine_servizi/Tributi/tributi_link_servizi_online
  phone: +39 020202
  email: io-testing@teamdigitale.governo.it

01CT1SH9K4E4017NWSY4S1KWW6:
  description: |
    Il servizio di Tributi di ACI.
    Tramite IO potrai:

      * Ricevere notifiche 15 giorni prima la scadenza del tuo bollo auto e procedere tempestivamente con il pagamento
      * Ricevere notifiche 15 giorni prima che scattino degli interessi di mora sul tuo bollo scaduto e non ancora pagato, e pagare direttamente
    
  tos_url: https://bollo.aci.it/#/main/home
  privacy_url: http://www.aci.it/per-la-navigazione-del-sito/privacy-policy-e-cookie-policy.html
  web_url: http://www.aci.it/i-servizi/servizi-online/bollo-auto.html
  email: io-testing@teamdigitale.governo.it

01CT1WBV3FJRJ1TKEC4R5N6D82:
  description: |
    Il servizio dei Certidicati di proprietà di ACI.
    Tramite IO potrai:

      * Ricevere notifiche sul rilascio dei tuoi certificati di prioprietà
      * Ottenere i certificati di proprietà riguardanti i tuoi veicoli

  tos_url: https://iservizi.aci.it/consultacdpd/
  privacy_url: http://www.aci.it/per-la-navigazione-del-sito/privacy-policy-e-cookie-policy.html
  web_url: http://www.aci.it/i-servizi/servizi-online/certificato-di-proprieta-digitale.html
  email: io-testing@teamdigitale.governo.it

01CT1WDDYHXKW1AP6199K8DTK6:
  description: |
    Il servizio dell’Anagrafe del Comune di Milano.
    Tramite IO potrai:

      * Ricevere notifiche sulla scadenza dei tuoi documenti di identità

  privacy_url: http://www.palazzorealemilano.it/wps/portal/luogo/palazzoreale/footer/linkinterni/privacy
  web_url: http://www.comune.milano.it/wps/portal/ist/it/servizi/servizionline/pagine_servizi/anagrafe/anagrafe_link_servizi_online
  phone: +39 020202
  email: io-testing@teamdigitale.governo.it

01CT1WFXH4Z0XJWHP1MB4GN3QD:
  description: |
    Il servizio Scolastico del Comune di Milano.
    Tramite IO potrai:

      * Ricevere notifiche su comunicazioni relative all'apertura delle iscrizioni al nido di infanzia, mensa e trasporti
      * Ricevere notifiche e pagamere le rette scolastiche, delle mense e dei trasporti.

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: http://www.comune.milano.it/wps/portal/ist/it/servizi/educazione
  email: io-testing@teamdigitale.governo.it

01CT1WGM427E122VJKTXJ1RQDH:
  description: |
    Il servizio di Comunicazione del Comune di Milano.
    Tramite IO potrai:

      * Ricevere, in tempo reale, notifiche di avviso (preallarme o allarme) su criticità ambientali,
        allarmi di protezione civile, ordinanze emesse e messaggi informativi a carattere istituzionale.

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: https://www.comune.milano.it/
  email: io-testing@teamdigitale.governo.it

01CT1WHDPJWNPJRKQ1X8F95P2K:
  description: |
    Il servizio della Polizia Municipale del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche relative pagamenti necessati per sanzioni al Codice della Strada
      * Effettuare il pagamento delle sanzioni per violazioni al Codice della Strada

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://servizionline.comune.palermo.it/portcitt/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=40&S=30
  phone: 0916954211
  email: io-testing@teamdigitale.governo.it
  address: Via Dogali n.29
  pec: comandopoliziamunicipale@cert.comune.palermo.it

01CT1WHSHWAGRF8SMYS6CSR5FS:
  description: |
    Il servizio sulla Mobilità Urbana del Comune di Palermo.
    Tramite IO potrai:

      * Essere avvisato in tempi utili sulla scadenza del tuo permesso ZTL
      * Richiedere e pagare (se necessario) il tuo nuovo permesso ZTL

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://ztl.comune.palermo.it/ztl/jsp/home.do?sportello=ztl
  phone: 0917401606
  email: io-testing@teamdigitale.governo.it
  address: Via Ausonia n.69
  pec: mobilitaurbana@cert.comune.palermo.it
  app_ios: https://itunes.apple.com/it/app/ztl-palermo/id1166868545?mt=8
  app_android: https://play.google.com/store/apps/details?id=it.korec.palermomobilita

01CT1WJ8D0AVSRV9N7S2NM2JBF:
  description: |
    Il servizio dei Tributi del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche quando un nuovo documento viene inserito nel tuo Cassetto Tributi

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://servizionline.comune.palermo.it/portcitt/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=10&S=40
  phone: 091 7404508; 091 7404501
  address: Piazza G. Cesare n.6
  email: io-testing@teamdigitale.governo.it
  pec: settoretributi@cert.comune.palermo.it

01CT1WJKVB6M0SDNXHJHJJBDX9:
  description: |
    Il servizio dei Tributi del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche, in data utile, sulla data/ora degli appuntamenti presso l'Ufficio Tributi e inserire un promemoria nel calendario
      * Ricevere notifiche in caso di eventuali disdette da parte dell’Ufficio

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://servizionline.comune.palermo.it/portcitt/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=10&SERCOD=1084&sportello=portcitt
  phone: 091 7404508; 091 7404501
  address: Piazza G. Cesare n.6
  email: io-testing@teamdigitale.governo.it
  pec: settoretributi@cert.comune.palermo.it

01CT1WK81HJA0KGENDPEPXCJXJ:
  description: |
    Il servizio della Protezione Civile del Comune di Palermo.
    Tramite IO potrai:
  
      * Ricevere, in tempo reale, notifiche di avviso (preallarme o allarme) su criticità ambientali

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  email: io-testing@teamdigitale.governo.it

01CT1WM5VX706MDQ0DM4ZVAGAG:
  description: |
    Il servizio di sussidio economico ai cittadini del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche quando il sussidio economico ti è stato accreditato sul conto

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  email: io-testing@teamdigitale.governo.it

01CT1WMH651JE5DGP7RX9MKV6G:
  description: |
    Il servizio Scolastico del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche su comunicazioni relative all'apertura delle iscrizioni al nido di infanzia, mensa e trasporti
      * Ricevere notifiche e pagamere le rette scolastiche, delle mense e dei trasporti.

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  email: io-testing@teamdigitale.governo.it
