#
# This file contains the metadata for the services approved in the IO app
#
# The key for each service is the serviceId.
# All fields are optional.
#
---
5a563817fcc896087002ea46c49a:
  description: |
    IO è l’applicazione sperimentale (attualmente in fase di closed beta) che permette ai cittadini
    di gestire direttamente dal proprio smartphone i rapporti con la Pubblica Amministrazione Italiana
    e l’accesso ai servizi pubblici.

    Ti invierà messaggi su come usare l'applicazione, aggiornamenti sul progetto o sulle funzionlità dell'app,
    richieste di feedback e altre istruzioni utili alla sperimentazione.
    
    IO è un progetto della Presidenza del Consiglio dei Ministri realizzato dal Team per la Trasformazione Digitale
    in collaborazione con Agid.

  web_url: https://io.italia.it
  email: io-testing@teamdigitale.governo.it

5a25abf4fcc89605c082f042c49a:
  description: |
    Il servizio dell’Anagrafe del Comune di Milano. Tramite IO potrai:

    * Ricevere notifiche sulla scadenza dei tuoi documenti di identità

  web_url: http://www.comune.milano.it/wps/portal/ist/it/servizi/servizionline/pagine_servizi/anagrafe/anagrafe_link_servizi_online
  privacy_url: http://www.palazzorealemilano.it/wps/portal/luogo/palazzoreale/footer/linkinterni/privacy
  phone: +39 02 0202
  email: anagrafe@comune.milano.it
  pec: anagrafe@pec.comune.milano.it

5b4f7512a9ab400f2417f0ccc49a:
  description: |
    Il servizio della Polizia Municipale del Comune di Cagliari. Tramite IO potrai:

      * Riceve notifiche relative pagamenti necessati per sanzioni al Codice della Strada
      * Effettuare il pagamento delle sanzioni per violazioni al Codice della Strada

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://www.comune.cagliari.it/portale/it/servizio_polizia_municipale.page
  address: Via Avicenna - 09131 Cagliari
  phone: +39 0800230606
  email: pm.ced@comune.cagliari.it
  pec: poliziamunicipale@comune.cagliari.legalmail.it

5b928ef65aaa2928c0319563c49a:
  description: |
    Il servizio della Protezione Civile del Comune di Cagliari. Tramite IO potrai:

      * Ricevere, in tempo reale, notifiche di avviso (preallarme o allarme) su criticità ambientali.

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://servizi.comune.cagliari.it/portale/it/servizio_sms.page
  address: Via Giuseppe Mercalli, 31 - 09129 Cagliari
  phone: +39 070 6776905
  email: protezione.civile@comune.cagliari.it
  pec: protocollogenerale@comune.cagliari.legalmail.it

5b87a75d34234f1170e79deec49a:
  description: |
    Il servizio sulla Viabilità del Comune di Cagliari. Tramite IO potrai:

      * Essere avvisato in tempi utili sulla scadenza del tuo permesso ZTL
      * Richiedere e pagare (se necessario) il tuo nuovo permesso ZTL

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://servizi.comune.cagliari.it/portale/it/richiesta_rinn_pass_ztl.page
  address: Piazza A. De Gasperi, 2 - 09125 Cagliari
  phone: +39 070 6778303
  email: ufficioztl@comune.cagliari.it
  pec: protocollogenerale@comune.cagliari.legalmail.it

