swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
basePath: /pp-restapi-CD
tags:
  - name: bancomat-controller
    description: Bancomat Controller

produces:
  - application/json
paths:
  /v1/bancomat/abi:
    get:
      tags:
        - bancomat-controller
      summary: getAbi
      operationId: getAbiUsingGet
      consumes:
        - application/json
      parameters:
        - name: size
          in: query
          description: size
          required: false
          type: string
          default: 10
        - name: start
          in: query
          description: start
          required: false
          type: string
          default: 0
        - name: abiQuery
          in: query
          description: abiQuery
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AbiResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
  /v1/bancomat/pans:
    get:
      tags:
        - bancomat-controller
      summary: getPans
      operationId: getPansUsingGet
      consumes:
        - application/json
      parameters:
        - name: abi
          in: query
          description: abi
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Cards'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
  /v1/bancomat/add-wallets:
    post:
      tags:
        - bancomat-controller
      summary: add Bancomat card
      operationId: addWalletsUsingPost
      consumes:
        - application/json
      parameters:
        - name: size
          in: body
          schema:
            $ref: '#/definitions/Cards'
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Wallets'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
  /v2/wallet:
    get:
      tags:
        - wallet-controller
      summary: getWallets
      operationId: getWalletsUsingGET
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Wallets'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Cards:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Card'
  Card:
    type: object
    properties:
      abi:
        type: string
      cardNumber:
        type: string
      cardPartialNumber:
        type: string
      expiringDate:
        type: string
        pattern: "yyyy-MM-dd"
        format: date
      productType:
        type: string
        enum:
          - PP
          - DEB
      tokens:
        type: array
        items:
          type: string
      validityState:
        type: string
        enum:
          - V
          - BR
    title: Card

  AbiResponse:
    type: object
    properties:
      total:
        type: integer
      start:
        type: integer
      size:
        type: integer
      data:
        type: array
        items:
          $ref: '#/definitions/Abi'
  Abi:
    type: object
    properties:
      abi:
        type: string
      name:
        type: string
      logoUrl:
        type: string

  Wallets:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Wallet'
  Wallet:
    type: object
    properties:
      idWallet:
        type: integer
      enableableFunctions:
        type: array
        items:
          type: string
          enum:
            - pagoPA
            - BPD
            - FA
      pagoPA:
        type: boolean
      onboardingChannel:
        type: string
        enum:
          - IO
          - WISP
          - EXT
      favourite:
        type: boolean
      createDate:
        type: string
        format: date
        pattern:  "yyyy-MM-dd"
      updateDate:
        type: string
        format: date
        pattern:  "yyyy-MM-dd"
      info:
        $ref: '#/definitions/CardInfo'

  CardInfo:
    type: object
    properties:
      holder:
        type: string
      blurredNumber:
        type: string
        example: "0000"
      hashPan:
        type: string
      expireMonth:
        type: string
        pattern: "MM"
      expireYear:
        type: string
        pattern: "yyyy"
      brand:
        type: string
      brandLogo:
        type: string
      type:
        type: string
        enum:
          - PP
          - DEB
      issuerAbiCode:
        type: string
      htokenList:
        type: array
        items:
          type: string



      